name: PHPStan Level 8

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon'
      - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install PHPStan
        run: composer require phpstan/phpstan --dev

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src tests --level=8
