name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts

      - name: Run Tests
        working-directory: packages/syntaxsapiens/logodev-laravel
        run: vendor/bin/pest
